server:
  port: 5080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${TASK_DB_HOST}:5432/taskdb"
    username: taskmaster-admin
    password: 1nf0M@t1cs
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:9080/auth/realms/taskmaster
          jwk-set-uri: http://${KEYCLOAK_HOST}:9080/auth/realms/taskmaster/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG