server:
  port: 5080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${TASK_DB_HOST}:5432/taskdb"
    username: taskmaster-admin
    password: 1nf0M@t1cs

# Can be set to false to disable security during local development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/taskmaster
          jwk-set-uri: http://localhost:9080/auth/realms/taskmaster/protocol/openid-connect/certs