version: '3'
services:
  taskdb:
    image: postgres:12
    volumes:
      - taskdb-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_MULTIPLE_DATABASES: taskdb,keycloakdb
      POSTGRES_USER: taskmaster-admin
      POSTGRES_PASSWORD: 1nf0M@t1cs
    networks:
      - docker-network
  
  keycloak:
   image: quay.io/keycloak/keycloak:latest
   environment:
     DB_VENDOR: POSTGRES
     DB_ADDR: taskdb
     DB_DATABASE: keycloakdb
     DB_USER: taskmaster-admin
     DB_SCHEMA: public
     DB_PASSWORD: 1nf0M@t1cs
#    KEYCLOAK_USER: admin
     KEYCLOAK_PASSWORD: keycloak
   ports:
     - 9080:8080
   depends_on:
     - taskdb
   networks:
    - docker-network

  taskservice:
    image:  udayspublic/taskservice:latest
    ports:
    - '5080:5080'
    depends_on:
    - taskdb
    - keycloak
    environment:
    - TASK_DB_HOST=taskdb
    - KEYCLOAK_HOST=keycloak
    networks:
     - docker-network
      
volumes:
  taskdb-data:

networks:
  docker-network:
    driver: bridge