# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file taskservice/pom.xml -Dmaven.test.skip=true
    - name: Upload jar for job 1
      uses: actions/upload-artifact@v1
      with:
          name: jarpack
          path: ./taskservice/target    
    
    
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download jar for job 2
        uses: actions/download-artifact@v1
        with:
          name: jarpack                   # The jar package will be checkout: jarpack/...jar 
      - name: Build the Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: taskservice/Dockerfile
          repository: udayspublic/taskservice
          build_args: JAR_FILE=$GITHUB_WORKSPACE/jarpack/*.jar 
          tags: 1.0
